[project]
name = "tinycontracts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
    "rich>=14.3.2",
    "typer>=0.21.1",
    "uvicorn>=0.40.0",
]
